version: '2'
services:
  auth-server:
    build: .
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - NPM_CONFIG_PRODUCTION=${NPM_CONFIG_PRODUCTION}
      - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      - MONGO_AUTH_URI=${MONGO_AUTH_URI}
      - KEY_PATH=${KEY_PATH}
      - CERT_PATH=${CERT_PATH}
      - SYSTEM_EMAIL=${SYSTEM_EMAIL}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - LOGIN_ATTEMPTS_FOR_IP=${LOGIN_ATTEMPTS_FOR_IP}
      - LOGIN_ATTEMPTS_FOR_IP_AND_USER=${LOGIN_ATTEMPTS_FOR_IP_AND_USER}
      - LOGIN_ATTEMPTS_LOG_EXPIRATION=${LOGIN_ATTEMPTS_LOG_EXPIRATION}
      - REQUIRE_ACCOUNT_VERIFICATION=${REQUIRE_ACCOUNT_VERIFICATION}
      - DISABLE_SIGNUP=${DISABLE_SIGNUP}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USE_SSL=${SMTP_USE_SSL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - API_VERSION=${API_VERSION}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_PRIVATE_KEY_PATH=${JWT_PRIVATE_KEY_PATH}
      - JWT_CERT_PATH=${JWT_CERT_PATH}
      - AUTH_THIRD_PART_WEBSERVICE_URI=${AUTH_THIRD_PART_WEBSERVICE_URI}
      - AUTH_THIRD_PART_USERINFO_ENDPOINT=${AUTH_THIRD_PART_USERINFO_ENDPOINT}
      - AUTH_THRID_PART_GOOGLE_OAUTH_CORS_FILTER=${AUTH_THRID_PART_GOOGLE_OAUTH_CORS_FILTER}
      - SENTRY_TOKEN_AUTH=${SENTRY_TOKEN_AUTH}
      - AUTHENT_LOG_FILE_PATH=${AUTHENT_LOG_FILE_PATH}
      - AUTH_SERVER_PREFIX=${AUTH_SERVER_PREFIX}
      - AUTH_SERVER_HOST=${AUTH_SERVER_HOST}
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
    depends_on:
      - mongodb
    volumes:
      - ./key:/etc/key
      - ./log:/usr/src/log
  mongodb:
      image: mongo:3.2
      restart: always
      container_name: mongodb_container
      command: /bin/bash -c "chown -R mongodb /var/log/mongodb; mongod --config /etc/mongodb/mongod.conf"
      volumes:
       - ./mongodb/log:/var/log/mongodb
       - ./mongodb/conf/mongod.conf:/etc/mongodb/mongod.conf
       - ./mongodb/data:/var/lib/mongodb